from datetime import datetime
from models import BookGenre, BookStatus


REAL_BOOKS = [
    {
        "book_title": "Сероглазый король",
        "book_year": 2024,
        "author_id": 1,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXIGky3OkmVbhQfUnJ2vLydWFdxR7SAAIXEGsbYQKRSYlOgjQJELYiAQADAgADbQADNgQ",
        "book_price": 600,
        "book_genre": BookGenre.POETRY,
        "book_quantity": 5,
    },
    {
        "book_title": "Исповедь хулигана",
        "book_year": 2018,
        "author_id": 2,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXImky3ibh40k3yergbQ5FA5H7azGKAAIeEGsbYQKRSUIo4EvXqPPKAQADAgADbQADNgQ",
        "book_price": 300,
        "book_genre": BookGenre.POETRY,
        "book_quantity": 5,
    },
    {
        "book_title": "Укрощение строптивой ",
        "book_year": 2014,
        "author_id": 3,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXJGky3qm7OUUdrzdr51PhS1kaQGMBAAIkEGsbYQKRSXcoRYD09fSfAQADAgADbQADNgQ",
        "book_price": 450,
        "book_genre": BookGenre.POETRY,
        "book_quantity": 4,
    },
    {
        "book_title": "Ворона и лисица",
        "book_year": 2016,
        "author_id": 4,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXJmky3xcoHlWSiEe4kCelvHA1vac3AAIxEGsbYQKRScREJXwavVVPAQADAgADbQADNgQ",
        "book_price": 350,
        "book_genre": BookGenre.POETRY,
        "book_quantity": 10,
    },
    {
        "book_title": "Король Лир",
        "book_year": 2005,
        "author_id": 3,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXKGky338NbQy8PC7isK1jRi0iqsGQAAI2EGsbYQKRSUdrkxH_UtqsAQADAgADbQADNgQ",
        "book_price": 800,
        "book_genre": BookGenre.POETRY,
        "book_quantity": 7,
    },
    {
        "book_title": "Отелло. Макбет",
        "book_year": 2018,
        "author_id": 3,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXKmky3-XwfP6iAAGLuo_FcoV8UcP3FwACSxBrG2ECkUm71nAjYWMFfwEAAwIAA20AAzYE",
        "book_price": 1100,
        "book_genre": BookGenre.POETRY,
        "book_quantity": 4,
    },
    {
        "book_title": "Евгений Онегин. Роман в стихах",
        "book_year": 2025,
        "author_id": 5,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXLGky4D7CpH5fAnfQhj3ow1got7ZFAAJTEGsbYQKRSddJTfdfrsxkAQADAgADbQADNgQ",
        "book_price": 400,
        "book_genre": BookGenre.POETRY,
        "book_quantity": 12,
    },
    {
        "book_title": "Реквием",
        "book_year": 2022,
        "author_id": 1,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXLmky4I2e2Io6ITZjA4KHrNtaU_m-AAJXEGsbYQKRST4VaapvmOyVAQADAgADbQADNgQ",
        "book_price": 600,
        "book_genre": BookGenre.POETRY,
        "book_quantity": 4,
    },
    {
        "book_title": "Облако в штанах",
        "book_year": 2012,
        "author_id": 6,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXM2ky4UAlwgn_vtPabxtKbqLrJKTIAAJgEGsbYQKRSeaXD_YZ9xR0AQADAgADbQADNgQ",
        "book_price": 550,
        "book_genre": BookGenre.POETRY,
        "book_quantity": 7,
    },
    {
        "book_title": "Стихотворения. Поэмы",
        "book_year": 2016,
        "author_id": 7,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXNWky4X5OGqCNWMJtuP1SJsMXzN8OAAJlEGsbYQKRSVUF-cWoec1-AQADAgADbQADNgQ",
        "book_price": 800,
        "book_genre": BookGenre.POETRY,
        "book_quantity": 4,
    },
    {
        "book_title": "Война и мир. Том №1",
        "book_year": 2023,
        "author_id": 8,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXS2ky8bXpAa8seWWzj4GSPDBhU40jAAKaC2sbYQKZSSmI90l6OopiAQADAgADeAADNgQ",
        "book_price": 450,
        "book_genre": BookGenre.CLASSIC,
        "book_quantity": 3,
    },
    {
        "book_title": "Гордость и предубеждение",
        "book_year": 2025,
        "author_id": 9,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXT2ky8sm6-Cn8JzhyXcj0cgW-nGoWAAKfC2sbYQKZSb9WkOh8QA02AQADAgADeAADNgQ",
        "book_price": 450,
        "book_genre": BookGenre.CLASSIC,
        "book_quantity": 10,
    },
    {
        "book_title": "Мастер и Маргарита",
        "book_year": 2025,
        "author_id": 10,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXUWky81bHgOjmLNGpXX8jpvq9VW4jAAKkC2sbYQKZSUdcMXv_Kfd0AQADAgADeQADNgQ",
        "book_price": 365,
        "book_genre": BookGenre.CLASSIC,
        "book_quantity": 10,
    },
    {
        "book_title": "Дракула",
        "book_year": 2025,
        "author_id": 11,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXVGky9AJhBKrPZyAc27eni1dCHm4bAAKtC2sbYQKZSYXBdCIMcKTRAQADAgADeQADNgQ",
        "book_price": 650,
        "book_genre": BookGenre.CLASSIC,
        "book_quantity": 12,
    },
    {
        "book_title": "Портрет Дориана Грея",
        "book_year": 2025,
        "author_id": 12,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXVmky9EwAAZL3LH_SuOD93Qym3c_kSQACtAtrG2ECmUlSqWNtrtGqgQEAAwIAA3kAAzYE",
        "book_price": 500,
        "book_genre": BookGenre.CLASSIC,
        "book_quantity": 14,
    },
    {
        "book_title": "Преступление и наказание",
        "book_year": 2025,
        "author_id": 13,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXWGky9L9bNIK2VpDpU7mINF4Xkr9CAAK5C2sbYQKZSc9vLU6voCEPAQADAgADeQADNgQ",
        "book_price": 355,
        "book_genre": BookGenre.CLASSIC,
        "book_quantity": 10,
    },
    {
        "book_title": "Братья Карамазовы",
        "book_year": 2025,
        "author_id": 13,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXWmky9ggQgYvBdX3_8mgoagtl9c9gAALDC2sbYQKZSdIJSHT0sNaeAQADAgADeQADNgQ",
        "book_price": 400,
        "book_genre": BookGenre.CLASSIC,
        "book_quantity": 5,
    },
    {
        "book_title": "Маленькие женщины",
        "book_year": 2025,
        "author_id": 14,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXXGky9lUcVwoH4L-1KnLb1e4Bj35KAALFC2sbYQKZSWew1gpX2ikVAQADAgADeQADNgQ",
        "book_price": 599,
        "book_genre": BookGenre.CLASSIC,
        "book_quantity": 7,
    },
    {
        "book_title": "451' по Фаренгейту",
        "book_year": 2025,
        "author_id": 15,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXXmky9ogf_969LVa-1mhbLcbpNo2PAALJC2sbYQKZSd0qDfrus3dMAQADAgADeQADNgQ",
        "book_price": 800,
        "book_genre": BookGenre.CLASSIC,
        "book_quantity": 7,
    },
    {
        "book_title": "Пиковая дама",
        "book_year": 2025,
        "author_id": 5,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXYGky9uFTfWlu4IEzogeTqF0q5-IbAALPC2sbYQKZSfwEzBXobwh8AQADAgADeAADNgQ",
        "book_price": 250,
        "book_genre": BookGenre.CLASSIC,
        "book_quantity": 23,
    },
    {
        "book_title": "Приключения Шерлока Холмса. Возвращение Шерлока Холмса",
        "book_year": 2022,
        "author_id": 16,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXYmky-MMDZnMytSLQq6nwpYdAL_67AALeC2sbYQKZSdaxA_s-9YscAQADAgADeQADNgQ",
        "book_price": 450,
        "book_genre": BookGenre.DETECTIVE,
        "book_quantity": 8,
    },
    {
        "book_title": "Грета",
        "book_year": 2025,
        "author_id": 17,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXZGky-XPmfAXAFMzgH60NplxiAT7HAALqC2sbYQKZSRUZEnY0TFJvAQADAgADeQADNgQ",
        "book_price": 700,
        "book_genre": BookGenre.DETECTIVE,
        "book_quantity": 4,
    },
    {
        "book_title": "Луна 84. Перерождение",
        "book_year": 2025,
        "author_id": 18,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXZmky-eBiRc489x6ZGTmVqFZnuuVLAALyC2sbYQKZSfeC_5mmTtUIAQADAgADeQADNgQ",
        "book_price": 1120,
        "book_genre": BookGenre.DETECTIVE,
        "book_quantity": 4,
    },
    {
        "book_title": "Поворот винта. Вечные истории",
        "book_year": 2025,
        "author_id": 19,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXaGky-zoxjlwab5Mclr94IO9omwQtAAIIDGsbYQKZST2FylEPtQABlAEAAwIAA3kAAzYE",
        "book_price": 700,
        "book_genre": BookGenre.DETECTIVE,
        "book_quantity": 5,
    },
    {
        "book_title": "220 метров",
        "book_year": 2022,
        "author_id": 20,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXamky-4IZDGyZ0wIM8MFyOx6XGA_RAAILDGsbYQKZSTiGp6CjOs_mAQADAgADeQADNgQ",
        "book_price": 950,
        "book_genre": BookGenre.DETECTIVE,
        "book_quantity": 3,
    },
    {
        "book_title": "Тайна Дома трех вязов",
        "book_year": 2021,
        "author_id": 21,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXbGky-9fdXdZrw301pnIQ5Jz3SiC6AAIODGsbYQKZSdTcWoh-1v12AQADAgADeQADNgQ",
        "book_price": 900,
        "book_genre": BookGenre.DETECTIVE,
        "book_quantity": 6,
    },
    {
        "book_title": "Убийство у алтаря",
        "book_year": 2020,
        "author_id": 22,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXbmky_Ch7zHJzaUIwOoZxBXWgC3bQAAIPDGsbYQKZSRz0n2beWNtMAQADAgADeQADNgQ",
        "book_price": 900,
        "book_genre": BookGenre.DETECTIVE,
        "book_quantity": 3,
    },
    {
        "book_title": "Конклав",
        "book_year": 2025,
        "author_id": 23,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXcGky_J8Fhq0LvQe6eYOmlakqHqNpAAITDGsbYQKZSZRUBOsJAAFiTwEAAwIAA3kAAzYE",
        "book_price": 1200,
        "book_genre": BookGenre.DETECTIVE,
        "book_quantity": 8,
    },
    {
        "book_title": "Агент на мягких лапах",
        "book_year": 2022,
        "author_id": 24,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXcmky_RLgQ1yX1cCPnSjCaEqZuXSoAAIUDGsbYQKZSSgrHK5pv395AQADAgADeQADNgQ",
        "book_price": 800,
        "book_genre": BookGenre.DETECTIVE,
        "book_quantity": 7,
    },
    {
        "book_title": "Кот да Винчи. Улыбка Анаконды",
        "book_year": 2013,
        "author_id": 25,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXdGky_VDxhFLCEhT-eArzifHLMDLoAAIXDGsbYQKZSa3AuE2OHpItAQADAgADeQADNgQ",
        "book_price": 1000,
        "book_genre": BookGenre.DETECTIVE,
        "book_quantity": 7,
    },
    {
        "book_title": "Повелитель мух",
        "book_year": 2021,
        "author_id": 26,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXdmkzHNxR9joEAAH10nJwMw23liq4FwACVg1rG2ECmUk6wHl-1X2ycwEAAwIAA3kAAzYE",
        "book_price": 500,
        "book_genre": BookGenre.SCIENCEFICTION,
        "book_quantity": 6,
    },
    {
        "book_title": "О дивный новый мир",
        "book_year": 2022,
        "author_id": 27,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXeGkzHW4l7odpLVF_IdA94-ArYfT-AAJYDWsbYQKZScAYZezUi0nzAQADAgADeQADNgQ",
        "book_price": 600,
        "book_genre": BookGenre.SCIENCEFICTION,
        "book_quantity": 8,
    },
    {
        "book_title": "Солярис",
        "book_year": 2023,
        "author_id": 28,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXemkzHdbLHfzW-dl59NTGjHgVUi1kAAJaDWsbYQKZSbog_0Jbx6k8AQADAgADeQADNgQ",
        "book_price": 450,
        "book_genre": BookGenre.SCIENCEFICTION,
        "book_quantity": 6,
    },
    {
        "book_title": "Дюна",
        "book_year": 2024,
        "author_id": 29,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXfGkzHg9jDOkBn1G6jMYQX-SQIucwAAJdDWsbYQKZSQG7gr3aXqfiAQADAgADeQADNgQ",
        "book_price": 700,
        "book_genre": BookGenre.SCIENCEFICTION,
        "book_quantity": 12,
    },
    {
        "book_title": "Бегущий человек",
        "book_year": 2025,
        "author_id": 30,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXfmkzHkxtC6vDx563ZadJ8NSBNN0XAAJfDWsbYQKZScdI7Ul-bFD9AQADAgADeQADNgQ",
        "book_price": 800,
        "book_genre": BookGenre.SCIENCEFICTION,
        "book_quantity": 15,
    },
    {
        "book_title": "Автостопом по Галактике",
        "book_year": 2023,
        "author_id": 31,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXgGkzHq3aa7X-XGAkbdE0tijby036AAJiDWsbYQKZSd2dB5iRrZhRAQADAgADeQADNgQ",
        "book_price": 900,
        "book_genre": BookGenre.SCIENCEFICTION,
        "book_quantity": 14,
    },
    {
        "book_title": "Двадцать тысяч лье под водой",
        "book_year": 2024,
        "author_id": 32,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXgmkzHv87B_YvXPArUjGLVyECKLnkAAJkDWsbYQKZSUfRy74-Dr78AQADAgADeQADNgQ",
        "book_price": 900,
        "book_genre": BookGenre.SCIENCEFICTION,
        "book_quantity": 16,
    },
    {
        "book_title": "День триффидов",
        "book_year": 2025,
        "author_id": 33,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXhGkzH1nnQr6RIQ9GZt7tMrsOtFxyAAJpDWsbYQKZSXhYWXjrp6eqAQADAgADeQADNgQ",
        "book_price": 900,
        "book_genre": BookGenre.SCIENCEFICTION,
        "book_quantity": 18,
    },
    {
        "book_title": "Машина времени. Человек-невидимка: романы",
        "book_year": 2025,
        "author_id": 34,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXhmkzH94h9JoTN8pXmg3--Zdo902MAAJrDWsbYQKZSSSksvHOhvS8AQADAgADeQADNgQ",
        "book_price": 850,
        "book_genre": BookGenre.SCIENCEFICTION,
        "book_quantity": 12,
    },
    {
        "book_title": "Парень из Колорадо",
        "book_year": 2025,
        "author_id": 30,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXiGkzIFHusZZcxSUa7bLZxAT4iSG-AAKIDWsbYQKZSfObnHnwHfPMAQADAgADeQADNgQ",
        "book_price": 450,
        "book_genre": BookGenre.SCIENCEFICTION,
        "book_quantity": 10,
    },
    {
        "book_title": "Они вернутся. Книга первая",
        "book_year": 2023,
        "author_id": 35,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXjGkzIf9vYvK_R3Q0RA00XJjbCs7yAAKNDWsbYQKZSXh9GN3xCawNAQADAgADeQADNgQ",
        "book_price": 900,
        "book_genre": BookGenre.HORROR,
        "book_quantity": 12,
    },
    {
        "book_title": "Клыки",
        "book_year": 2025,
        "author_id": 36,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXjmkzIkU5OEJeUB7ibtTD1XBKKNc_AAKODWsbYQKZSappro7qgjOjAQADAgADeQADNgQ",
        "book_price": 1500,
        "book_genre": BookGenre.HORROR,
        "book_quantity": 14,
    },
    {
        "book_title": "Имя на камне",
        "book_year": 2025,
        "author_id": 37,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXkGkzInXL_K0vl1CxmLFF1qYj1GRvAAKPDWsbYQKZSS5erL3oGKxxAQADAgADeQADNgQ",
        "book_price": 1400,
        "book_genre": BookGenre.HORROR,
        "book_quantity": 19,
    },
    {
        "book_title": "Миры Ктулху",
        "book_year": 2025,
        "author_id": 38,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXkmkzIq7RhqbCj5z5ZTo_-_yEqvdOAAKRDWsbYQKZSZ0qkasW2F0AAQEAAwIAA3kAAzYE",
        "book_price": 1300,
        "book_genre": BookGenre.HORROR,
        "book_quantity": 14,
    },
    {
        "book_title": "Четыре сезона",
        "book_year": 2023,
        "author_id": 30,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXlGkzItIQf12eOYPpX9ctlIOPCujlAAKSDWsbYQKZSVhJhH6Cw5CpAQADAgADeQADNgQ",
        "book_price": 600,
        "book_genre": BookGenre.HORROR,
        "book_quantity": 16,
    },
    {
        "book_title": "На коне бледном",
        "book_year": 2024,
        "author_id": 39,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXlmkzIv7AckdFKsI1Slretr81Lil4AAKTDWsbYQKZScQlxek2m6q3AQADAgADeQADNgQ",
        "book_price": 800,
        "book_genre": BookGenre.HORROR,
        "book_quantity": 19,
    },
    {
        "book_title": "Бессонница",
        "book_year": 2024,
        "author_id": 30,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXmGkzIydW6iHhMWpyjnFlnfAh3y5NAAKWDWsbYQKZSQ8-Ir8LmdupAQADAgADeQADNgQ",
        "book_price": 900,
        "book_genre": BookGenre.HORROR,
        "book_quantity": 12,
    },
    {
        "book_title": "Дети тьмы - 2: летящие в ночи",
        "book_year": 2023,
        "author_id": 40,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXmmkzI17xQtJWWymwY0Krrm3eQ77NAAKYDWsbYQKZSY3yh6VucezQAQADAgADeQADNgQ",
        "book_price": 2000,
        "book_genre": BookGenre.HORROR,
        "book_quantity": 9,
    },
    {
        "book_title": "Черная Пасть",
        "book_year": 2025,
        "author_id": 41,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXnGkzI5SS3NAomkupkjEmS_1Ap6nXAAKaDWsbYQKZSX98y4-2N379AQADAgADeQADNgQ",
        "book_price": 1200,
        "book_genre": BookGenre.HORROR,
        "book_quantity": 12,
    },
    {
        "book_title": "Шепот гремучей лощины",
        "book_year": 2024,
        "author_id": 42,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXnmkzI9OR3adsxlFCGthLKPeKSG3SAAKdDWsbYQKZSV1Dx77z3CtmAQADAgADeQADNgQ",
        "book_price": 1000,
        "book_genre": BookGenre.HORROR,
        "book_quantity": 8,
    },
    {
        "book_title": "Ведьмак. Последнее желание",
        "book_year": 2024,
        "author_id": 43,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXoGkzJRVGKXgWYAeI-KaXK-GLtaoWAAKjDWsbYQKZSeZ3E7hBjjAvAQADAgADeQADNgQ",
        "book_price": 800,
        "book_genre": BookGenre.FANTASY,
        "book_quantity": 9,
    },
    {
        "book_title": "Некрономикон. Книга запретных тайн",
        "book_year": 2024,
        "author_id": 38,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXomkzJT5tq5Ut3WS5jjyy9IyVfOvJAAKlDWsbYQKZST_lLjaIm3nKAQADAgADeQADNgQ",
        "book_price": 1000,
        "book_genre": BookGenre.FANTASY,
        "book_quantity": 14,
    },
    {
        "book_title": "Сновичи",
        "book_year": 2025,
        "author_id": 44,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXpGkzJWa-9f6micCOC4qCUz5N1UEXAAKmDWsbYQKZSTXJxVOSOyhxAQADAgADeQADNgQ",
        "book_price": 900,
        "book_genre": BookGenre.FANTASY,
        "book_quantity": 14,
    },
    {
        "book_title": "Невеста Ноября",
        "book_year": 2023,
        "author_id": 45,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXpmkzJZMdRqU8V1epilchNZZPV2t_AAKoDWsbYQKZSbsDiJYYMveYAQADAgADeQADNgQ",
        "book_price": 600,
        "book_genre": BookGenre.FANTASY,
        "book_quantity": 9,
    },
    {
        "book_title": "Час быка",
        "book_year": 2024,
        "author_id": 46,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXqGkzJdEuQ0vcXItv8prOLBNlTWchAAKpDWsbYQKZSZHqkWDlCQ8YAQADAgADeQADNgQ",
        "book_price": 600,
        "book_genre": BookGenre.FANTASY,
        "book_quantity": 14,
    },
    {
        "book_title": "Человек-амфибия",
        "book_year": 2025,
        "author_id": 47,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXqmkzJgL4ZuTzI61YM1sZ-KenbcIAA6wNaxthAplJV7aLgoFfu2ABAAMCAAN5AAM2BA",
        "book_price": 900,
        "book_genre": BookGenre.FANTASY,
        "book_quantity": 14,
    },
    {
        "book_title": "Станция Лихо",
        "book_year": 2025,
        "author_id": 44,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXrGkzJiWbS2-MjHlj3qzpeJRm-8QZAAKuDWsbYQKZScOzAoSr4AnMAQADAgADeQADNgQ",
        "book_price": 900,
        "book_genre": BookGenre.FANTASY,
        "book_quantity": 15,
    },
    {
        "book_title": "Тайна третьей планеты",
        "book_year": 2024,
        "author_id": 48,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXrmkzJk8pG00CZPmeNMLsXIjyBaZNAALODWsbYQKZSZOCzM7ih6AMAQADAgADeQADNgQ",
        "book_price": 400,
        "book_genre": BookGenre.FANTASY,
        "book_quantity": 9,
    },
    {
        "book_title": "Долгая Прогулка",
        "book_year": 2025,
        "author_id": 30,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXsGkzJnCvBnd6cyOEGa4WI6w1_Ka7AALPDWsbYQKZSQRi0ls8J7hjAQADAgADeQADNgQ",
        "book_price": 850,
        "book_genre": BookGenre.FANTASY,
        "book_quantity": 6,
    },
    {
        "book_title": "Империя проклятых",
        "book_year": 2025,
        "author_id": 49,
        "book_status": BookStatus.IN_STOCK,
        "book_in_stock": True,
        "book_photo_id": "AgACAgIAAxkBAAIXsmkzJrkP1_a-yoTMKhShR4G7HTTUAALQDWsbYQKZSXeVvo7FHDztAQADAgADeQADNgQ",
        "book_price": 1000,
        "book_genre": BookGenre.FANTASY,
        "book_quantity": 9,
    },
]
